stages:
    - build
    - deploy
    - update

variables:
  CONTAINER_RELEASE_API: "docker-registry.beta.innovation.insee.eu/conjoncture1/dataviz-conj"

package:
  # Use stage build here, so the pages job may later pickup the created site.
  stage: build
  tags:
    - maven
  script:
    - 'docker build -t $CONTAINER_RELEASE_API .'
    - 'docker push $CONTAINER_RELEASE_API'

deploy:
  stage: deploy
  tags:
    - maven
  script:
    - 'APP_ID=`cat marathon.json | jq .id -r`'
    - 'cat marathon.json | envsubst | curl -d@- -H "Content-Type: application/json" -X PUT http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID?force=true'
    - 'curl -X POST http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID/restart?force=true'
  only:
    - master

update:
   stage: update
   script:
    - 'chmod +x ./data_update.sh'
   # - './data_update.sh'
   # - 'Rscript "./function/data_update.R"' 
