stages:
    - build
    - deploy

variables:
  CONTAINER_RELEASE_API: "docker-registry.beta.innovation.insee.eu/sic/divers/dataviz_conj"

package:
  # Use stage build here, so the pages job may later pickup the created site.
  stage: build
  tags:
    - maven
  script:
    - 'docker build -t $CONTAINER_RELEASE_API .'
    - 'docker push $CONTAINER_RELEASE_API'
  only:
    - master@sic/divers/dataviz_conj

deploy:
  stage: deploy
  only:
    - master@sic/divers/dataviz_conj
  tags:
    - maven
  script:
    - 'APP_ID=`cat marathon.json | jq .id -r`'
    - 'curl -d@marathon.json -H "Content-Type: application/json" -X PUT http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID?force=true'
    - 'curl -X POST http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID/restart?force=true'
  only:
    - master
#  environment:
#    name: prod
#    url: http://dataviz_conj.dev.innovation.insee.eu
