
stages:
    - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export container=docker 
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --registry-mirror registry-cache.lab.sspcloud.fr --destination $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG

#update:
   #stage: update
   #image: git-registry.lab.sspcloud.fr/hadrilec/graffiti-env:latest
   #script:
    #- 'chmod +x ./data_update.sh'
    #- 'echo $ACCESS_KEY_ID'
    #- './entrypoint.sh'
    #- ulimit -s 100000 # enlarge stack limit to 16 megs
    #- R --slave -e 'Cstack_info()["size"]'
    #- Rscript "./function/data_update.R" $ACCESS_KEY_ID $SECRET_ACCESS_KEY
