apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: graffiti
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
  - graffiti.inseefrlab.com
rules:
  - host: graffiti.inseefrlab.com
  http:
    paths:
      - path: /
      backend:
        serviceName: graffiti
        servicePort: http