apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graffiti
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - graffiti.lab.sspcloud.fr
  rules:
    - host: graffiti.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: graffiti
                port: 
                  number: 80
